package com.example.dynamodb.model;

import java.util.Objects;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
//@ToString
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "ORDERS_TBL")
public class Order {

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;

	//@DynamoDBAttribute
	//private String orderId;
	@DynamoDBAttribute
	private String name;

	@DynamoDBAttribute
	private int qty;

	@DynamoDBAttribute
	private double price;

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Order other = (Order) obj;
		return id == other.id && Objects.equals(name, other.name)
				&& Double.doubleToLongBits(price) == Double.doubleToLongBits(other.price) && qty == other.qty;
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, name, price, qty);
	}

}
